# BungeeNCPNotify Configuration

general:
  # Toggle if the plugin should check for updates and auto-update the plugin (recommended).
  enable-updater: true
  # Toggle if a notification should get sent to other servers.
  enable-send: true
  # Toggle if notifications from other servers should get received and handled.
  enable-receive: true
   # Set how much time should pass until another notification gets sent (in seconds).
  notify-cooldown: 90
  # Toggle if no notification should get sent when a staff member is online on the server.
  check-staff: true
  # Notification that gets sent to the other servers
  report-message: '&c%player% &efailed check on &c%server%&e: &c%check% &e(&cVL: %violation%&e)'

# CHECKS:
#   CATEGORY:
#     CHECK: VIOLATION
# You can set here the minimum required violation, which must be achieved so that the player gets reported to the other servers.
# Set violation to 0 or lower to disable the notification for the specific check.
# You do not have to set violation to -1 if the check was disabled in the NoCheatPlus configuration.
checks:
  blockbreak:
    direction: 15
    fastbreak: 2
    frequency: 8
    noswing: 15
    reach: 8
    wrongblock: 15
  blockinteract:
    direction: 15
    reach: 8
    speed: 300
    visible: 15
  blockplace:
    autosign: 15
    direction: 15
    fastplace: 150
    reach: 8
    noswing: 15
    speed: 225
  chat:
    color: 2
    commands: -1
    captcha: -1
    text: -1
    relog: -1
  combined:
    bedleave: 2
    improbable: 2
    munchhausen: 150
  fight:
    angle: 375
    critical: 75
    direction: 30
    fastheal: 15
    godmode: 2
    noswing: 15
    reach: 15
    selfhit: 2
    speed: 2
  inventory:
    drop: 2
    fastclick: 75
    instantbow: 23
    instanteat: 2
    fastconsume: 2
    gutenberg: 2
  moving:
    creativefly: 150
    morepackets: 15
    morepacketsvehicle: 15
    nofall: 2
    passable: 15
    survivalfly: 150
  net:
    flyingfrequency: -1
    keepalivefrequency: 15